version: '3.8'

services:
  app:
    image: notesy
    build: .
    ports:
      - "3000:3000"

    depends_on:
      - server
    volumes:
      - .:/app

  server:
    build: ./server/
    ports:
      - "3001:3001"